name: Next js app

on:
 push:
  branches: [ main ]

jobs:
   build:
    runs-on: ubantu-latest

    steps:
       - name: checout repositary
         uses:  actions/checkout@v6.0.1

       - name: Setup Node js
         uses:  actions/setup-node@v6.1.0
         with:
           node-version:  22.x
           cache: 'npm'

       - name: install dependences
         run: npm install

       - name: Build Next Js App
         run: npm run build

       - name: Upload Bulid on Artifacts
         uses:  actions/upload-artifact@v6.0.0
         with:
           name: nextjs-build
           path: out/
   
  
